# Generated by Django 6.0 on 2025-12-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricBoiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название электрического котла', max_length=200, verbose_name='Наименование котла')),
                ('product_url', models.URLField(help_text='URL ссылка на товар на внешнем ресурсе', verbose_name='Ссылка на товар')),
                ('price', models.CharField(help_text='Цена товара', max_length=50, verbose_name='Цена')),
                ('country', models.CharField(blank=True, help_text='Страна-производитель котла', max_length=100, null=True, verbose_name='Страна производитель')),
                ('power', models.CharField(blank=True, help_text='Мощность котла в киловаттах', max_length=50, null=True, verbose_name='Мощность кВт')),
                ('power_regulation', models.CharField(blank=True, help_text='Тип регулировки мощности', max_length=100, null=True, verbose_name='Регулировка мощности')),
                ('heating_area', models.CharField(blank=True, help_text='Рекомендуемая площадь отопления', max_length=100, null=True, verbose_name='Площадь отопления, рекомендуемая до')),
                ('work_type', models.CharField(blank=True, help_text='Начальный режим работы котла', max_length=100, null=True, verbose_name='Начальный вариант работы')),
                ('self_work', models.CharField(blank=True, help_text='Возможность автономной работы', max_length=100, null=True, verbose_name='Возможность для работы самостоятельно')),
                ('water_heating', models.CharField(blank=True, help_text='Поддержка нагрева воды', max_length=100, null=True, verbose_name='Возможность для нагрева воды')),
                ('floor_heating', models.CharField(blank=True, help_text='Поддержка теплого пола', max_length=100, null=True, verbose_name='Возможность нагрева теплого пола')),
                ('expansion_tank', models.CharField(blank=True, help_text='Наличие расширительного бака', max_length=100, null=True, verbose_name='Расширительный бак')),
                ('circulation_pump', models.CharField(blank=True, help_text='Наличие циркуляционного насоса', max_length=100, null=True, verbose_name='Циркуляционный насос')),
                ('voltage', models.CharField(blank=True, help_text='Напряжение питания', max_length=100, null=True, verbose_name='Питание от сети, Вольт')),
                ('cable', models.CharField(blank=True, help_text='Тип кабеля подключения', max_length=100, null=True, verbose_name='Кабель подключения')),
                ('fuse', models.CharField(blank=True, help_text='Сила тока предохранителя', max_length=100, null=True, verbose_name='Предохранитель, А')),
                ('temp_range', models.CharField(blank=True, help_text='Диапазон рабочих температур', max_length=100, null=True, verbose_name='Диапазон выбираемых температур, °C')),
                ('efficiency', models.CharField(blank=True, help_text='Коэффициент полезного действия', max_length=100, null=True, verbose_name='КПД')),
                ('connection', models.CharField(blank=True, help_text='Тип подключения к системе отопления', max_length=50, null=True, verbose_name='Подключение к системе')),
                ('dimensions', models.CharField(blank=True, help_text='Размеры котла в миллиметрах', max_length=100, null=True, verbose_name='Габаритные размеры, мм')),
                ('wifi', models.CharField(blank=True, help_text='Поддержка WiFi подключения', max_length=100, null=True, verbose_name='Возможность подключения WiFi')),
                ('thermostat', models.CharField(blank=True, help_text='Возможность подключения термостата', max_length=100, null=True, verbose_name='Возможность подключения комнатного термостата')),
                ('thermostat_included', models.CharField(blank=True, help_text='Наличие термостата в комплекте', max_length=100, null=True, verbose_name='Комнатный термостат в комплекте')),
                ('outdoor_sensor', models.CharField(blank=True, help_text='Поддержка датчика уличной температуры', max_length=100, null=True, verbose_name='Возможно подключение датчика уличной температуры')),
                ('description', models.TextField(blank=True, help_text='Подробное описание котла', null=True, verbose_name='Описание')),
                ('documentation', models.URLField(blank=True, help_text='Ссылка на документацию/инструкцию', null=True, verbose_name='Инструкция по котлу (Документация)')),
                ('image_1', models.URLField(blank=True, help_text='URL первого изображения', null=True, verbose_name='Изображение 1')),
                ('image_2', models.URLField(blank=True, help_text='URL второго изображения', null=True, verbose_name='Изображение 2')),
                ('image_3', models.URLField(blank=True, help_text='URL третьего изображения', null=True, verbose_name='Изображение 3')),
                ('image_4', models.URLField(blank=True, help_text='URL четвертого изображения', null=True, verbose_name='Изображение 4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Электрический котел',
                'verbose_name_plural': 'Электрические котлы',
                'ordering': ['name'],
            },
        ),
    ]
