# Generated by Django 5.2.4 on 2025-12-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_customuser_avatar_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер корпуса'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна проживания'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица'),
        ),
    ]
