# Generated by Django 6.0 on 2026-01-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customuser_apartment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricboiler',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='electricboiler',
            name='temp_range',
        ),
        migrations.AddField(
            model_name='electricboiler',
            name='image_5',
            field=models.URLField(blank=True, help_text='URL пятого изображения', null=True, verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='electricboiler',
            name='temp_range_floor',
            field=models.CharField(blank=True, help_text='Диапазон температур для теплого пола', max_length=100, null=True, verbose_name='Диапазон выбираемых температур - теплый пол, °C'),
        ),
        migrations.AddField(
            model_name='electricboiler',
            name='temp_range_radiator',
            field=models.CharField(blank=True, help_text='Диапазон температур для радиаторного отопления', max_length=100, null=True, verbose_name='Диапазон выбираемых температур - радиаторное отопление, °C'),
        ),
    ]
