# Generated by Django 6.0 on 2026-01-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_electricboiler_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricboiler',
            name='temp_range',
            field=models.CharField(blank=True, help_text='Диапазон выбираемых температур (или значение радиаторного отопления)', max_length=100, null=True, verbose_name='Диапазон выбираемых температур, °C'),
        ),
    ]
