# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_electricboiler_temp_range"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Например: По г. Брест при сумме заказа от 1000 BYN",
                        max_length=300,
                        verbose_name="Название условия доставки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание стоимости и условий доставки (редактируемый текст)",
                        verbose_name="Стоимость и условия",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Меньшее значение — выше в списке",
                        verbose_name="Порядок отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка",
                "verbose_name_plural": "Доставка",
                "db_table": "delivery",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
