# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_add_delivery_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="description",
            new_name="value_text",
        ),
        migrations.AddField(
            model_name="delivery",
            name="value_number",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Стоимость в BYN или другое число — при необходимости оставьте пустым",
                max_digits=12,
                null=True,
                verbose_name="Числовое значение (BYN, кг и т.д.)",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="value_text",
            field=models.TextField(
                blank=True,
                help_text="Описание стоимости и условий доставки — вносится вручную",
                verbose_name="Текстовое значение (условия, примечания)",
            ),
        ),
    ]
