# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_delivery_value_number_and_rename_description_to_value_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Сумма в BYN (при необходимости; необязательное поле).",
                max_digits=12,
                null=True,
                verbose_name="Сумма",
            ),
        ),
    ]
