# Generated by Django 6.0 on 2026-03-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delivery_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='title',
            field=models.CharField(help_text='Для checkout (курьер): «км» — тариф за 1 км; «базов»/«подъезд»/«выезд» — фикс к сумме; «минимальн» — нижняя граница доставки; «макс»/«потолок» — верхняя; «бесплатн» + «доставк»/«курьер»/«заказ» — порог суммы заказа для бесплатной доставки.', max_length=300, verbose_name='Название условия доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='BYN. Км — за километр (начисление по начатым км); базов/подъезд — фикс; минимальн/макс — ограничения итога; бесплатн — мин. сумма заказа для 0 BYN доставки.', max_digits=12, null=True, verbose_name='Числовое значение (BYN, кг и т.д.)'),
        ),
    ]
