# Generated by Django 6.0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_delivery_title_alter_delivery_value_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="value_text",
        ),
    ]
