# Generated by Django 5.2.4 on 2026-03-30 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_delivery_value_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для id=1…id=4 (правила checkout по Бресту / не Бресту): стоимость доставки BYN. Для от/до — цена доставки (−1 менеджер, 0 бесплатно).', max_digits=12, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='title',
            field=models.CharField(help_text='Checkout (курьер): id=2 — Брест, сумма меньше числового значения → стоимость из суммы строки; id=1 — Брест, сумма больше числового значения → стоимость из суммы (после id=2); id=4 — не Брест, сумма меньше числового значения → стоимость из суммы; id=3 — не Брест, сумма больше числового значения → стоимость из суммы (после id=4). Далее строки «По г. Брест…» / «По Республике Беларусь…» от/до. Прочее — для справки.', max_length=300, verbose_name='Название условия доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для id=1 (Брест, больше), id=2 (Брест, меньше), id=3 (не Брест, больше), id=4 (не Брест, меньше): порог. Для строк «…при сумме заказа от/до»: порог. Иначе — по смыслу названия.', max_digits=12, null=True, verbose_name='Числовое значение (BYN, кг и т.д.)'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьером')], max_length=20, verbose_name='Способ доставки')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Страна')),
                ('region', models.CharField(blank=True, default='', max_length=100, verbose_name='Область')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='Район')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('street', models.CharField(blank=True, default='', max_length=200, verbose_name='Улица')),
                ('house_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер дома')),
                ('building_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Корпус')),
                ('apartment_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Квартира')),
                ('products_subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма заказа (товары), BYN')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость доставки, BYN')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итого к оплате, BYN')),
                ('payment_method', models.CharField(choices=[('cash_on_receipt', 'Наличными при получении'), ('card_online', 'Банковской картой онлайн'), ('card_on_receipt', 'Банковской картой при получении')], max_length=30, verbose_name='Способ оплаты')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон для связи')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'История заказов',
                'db_table': 'order_history',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID товара в каталоге')),
                ('product_name', models.CharField(max_length=300, verbose_name='Наименование товара')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ед., BYN')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма по строке, BYN')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.orderhistory', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'db_table': 'order_history_item',
                'ordering': ['id'],
            },
        ),
    ]
