# Generated by Django 5.2.4 on 2026-03-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='products_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость заказа, BYN'),
        ),
    ]
