# Generated by Django 5.2.4 on 2026-03-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_orderhistory_products_subtotal_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
