# Generated by Django 5.2.4 on 2026-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_orderhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('canceled_by_user', 'Отменен пользователем')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
