# Generated by Django 5.2.4 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_userquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='answer_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ответ отправлен на e-mail'),
        ),
    ]
